centro_de_estudio(itca).
centro_de_estudio(colegio_champagnat).
centro_de_estudio(colegio_santa_cecilia).
centro_de_estudio(escuela_alberto_masferrer).
centro_de_estudio(escuela_daniel_hernandez).
centro_de_estudio(escuela_jardines_de_la_sabana).
centro_de_estudio(escuela_quezaltepec).
centro_de_estudio(escuela_san_luis_gonzaga).
centro_de_estudio(parvularia_jose_maria_san_martin).
centro_de_estudio(escuela_america).
centro_de_estudio(escuela_walter_soundy).
centro_de_estudio(escuela_en_comercio_y_administracion).
centro_de_estudio(escuela_margarita_duran).
centro_de_estudio(colegio_mi_pincelito).
centro_de_estudio(escuela_marcelino_garcia_flamenco).
centro_de_estudio(escuela_canton_victoria).
centro_de_estudio(escuela_maria_mazzarello).
centro_de_estudio(colegio_manuel_gallardo).
centro_de_estudio(escuela_empresarial).
centro_de_estudio(colegio_madre_teresa_margarita_sanchez).
centro_de_estudio(colegio_heroes_de_cuscatlan).
centro_de_estudio(colegio_julio_verne).
centro_de_estudio(escuela_educacion_especial_santa_tecla).
centro_de_estudio(colegio_miguel_angel_gallardo).
centro_de_estudio(complejo_armando_bukele_kattan).
centro_de_estudio(superate).
centro_de_estudio(colegio_fatima).
centro_de_estudio(colegio_coralia_haydee_quiroz).
centro_de_estudio(colegio_utila_5_de_junio).
centro_de_estudio(colegio_luisa_de_marillac).
centro_de_estudio(colegio_jose_valdez).
centro_de_estudio(colegio_champagnat).
centro_de_estudio(colegio_belen).
centro_de_estudio(colegio_gustavo_adolfo_becquer).
centro_de_estudio(colegio_santa_cecilia).
centro_de_estudio(colegio_hispano_america).
centro_de_estudio(colegio_nazareth).
centro_de_estudio(universidad_tecnica_latinoamericana).
centro_de_estudio(escuela_de_comuniacion_monica_herrera).

centro_de_salud(hospital_san_rafael).
centro_de_salud(hospital_climosal).
centro_de_salud(hospital_merliot).
centro_de_salud(hospital_casa_de_salud).
centro_de_salud(hospital_climetecla).
centro_de_salud(centro_medico_integral).
centro_de_salud(unidad_de_salud_adalberto_aguilar).
centro_de_salud(unidad_de_salud_diaz_del_pinal).
centro_de_salud(policlinico_magisterial_de_santa_tecla).
centro_de_salud(clinicas_candray).
centro_de_salud(multiclinica_teclenia).
centro_de_salud(hospital_seguro_social_santa_tecla).
centro_de_salud(unidad_medica_isss_santa_tecla).
centro_de_salud(clinica_comunal_isss_ciudad_merliot).
centro_de_salud(clinica_comunal_isss_santa_monica).

gasolinera(puma_energy_trebol).
gasolinera(uno_delicias).
gasolinera(texaco_delicias).
gasolinera(uno_merliot).
gasolinera(texaco_merliot).
gasolinera(puma_energy_merliot).
gasolinera(texaco_servitec).
gasolinera(uno_utila).
gasolinera(servicio_iraheta).
gasolinera(texaco_la_skina).
gasolinera(uno_santa_tecla).
gasolinera(puma_energy_delicias).
gasolinera(puma_energy_itca).
gasolinera(dlc_santa_tecla).
gasolinera(servi_tecla).
gasolinera(puma_energy_holanda).

parque(las_araucarias).
parque(daniel_hernandez).
parque(de_la_familia).
parque(las_colinas).
parque(pinares_de_suiza).
parque(la_sabana_3).
parque(san_martin).
parque(adela_van_severen).
parque(los_girasoles).
parque(monte_sion).
parque(el_triangulo).
parque(pinares_de_suiza_2).
parque(san_jose).
parque(buena_vista_1).
parque(santa_monica).
parque(estremo_merliot).
parque(acovitt).
parque(miraflores).
parque(el_principito).
parque(san_rafael).
parque(jardines_de_la_sabana_2).
parque(fincas_de_asturias).
parque(cafetalon).

centro_comercial(santa_rosa).
centro_comercial(la_skina).
centro_comercial(plaza_santa_monica).
centro_comercial(plaza_merliot).
centro_comercial(el_greko).
centro_comercial(la_sabana).
centro_comercial(merliot_1).
centro_comercial(daniel_hernandez).
centro_comercial(portal_plaza).
centro_comercial(novocentro_santa_tecla).
centro_comercial(santa_ines).
centro_comercial(plaza_malta).
centro_comercial(las_ramblas).
centro_comercial(el_trebol).
centro_comercial(holanda).


